name: "build"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: docker://i386/centos:7
        with:
          entrypoint: /bin/bash
          args: ./build.sh
