name: "build"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: docker://i386/centos:7
        with:
          entrypoint: /bin/bash
          args: ./build.sh
      - name: Upload assets
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: eine/tip@master
        timeout-minutes: 15
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            archives/cldc-linux-i386.tar.xz
            archives/midp-linux-fb-i386.tar.xz
